name: cron

on:
  schedule:
    - cron: "0 22 * * *"
  dispatch_workflow:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: |
          curl --request POST \
          --url https://cookie-jelly.vercel.app/api/notification
